apiVersion: v2
name: starbyte
description: StarByte 全链路管理系统 Kubernetes Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - starbyte
  - management-system
  - go
  - react
maintainers:
  - name: StarByte Team
